In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Load data

data=pd.read_csv('IMDB Dataset.csv')

In [3]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [4]:
data.drop_duplicates(inplace=True)

In [5]:
data.shape

(49582, 2)

Text Preprocessing

In [6]:
#Lowercase
data['review']=data['review'].str.lower()

In [7]:
#REMOVE URL
import re
def remove_urls(text):
  if isinstance(text, str):
    text=re.sub(r"http\S+","",text)
  return text
data['review']=data['review'].apply(remove_urls)

In [8]:
data

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [9]:
#Remove the Unnecesary word
import re # Ensure re is imported, if not already
def remove_un(text):

  if isinstance(text, str):
    text=re.sub(r"[^A-Za-z0-9\s]","",text)
  return text
data['review']=data['review'].apply(remove_un)

In [10]:
#Removing Html Tag
import re # Ensure re is imported
def remove_html(text):
  if isinstance(text, str):
    text=re.sub('<.*?>','',text)
  return text
data['review']=data['review'].apply(remove_html)

In [11]:
#Tokeniniaxtion
import nltk
nltk.download("punkt")
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [12]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [13]:
text="I love coding in python"
token=word_tokenize(text)
print(token)

['I', 'love', 'coding', 'in', 'python']

In [14]:
#reove stop/unnecessary  word
def remove_stop(text):
  token=word_tokenize(text)
  stop_word=stopwords.words("english")
  for word in token:
    if word in stop_word:
      text.replace(word,"")
  return text
data['review']=data['review'].apply(remove_stop)

In [15]:
#Steming
from nltk.stem import PorterStemmer
def steming(text):
  ps=PorterStemmer()
  stream_words=[]
  tokens=word_tokenize(text)
  for token in tokens:
    stream_token=ps.stem(token)
    stream_words.append(stream_token)
  return " ".join(stream_words)
data['review']=data['review'].apply(steming)

In [16]:
data

                                                  review sentiment
0      one of the other review ha mention that after ...  positive
1      a wonder littl product br br the film techniqu...  positive
2      i thought thi wa a wonder way to spend time on...  positive
3      basic there a famili where a littl boy jake th...  negative
4      petter mattei love in the time of money is a v...  positive
...                                                  ...       ...
49995  i thought thi movi did a down right good job i...  positive
49996  bad plot bad dialogu bad act idiot direct the ...  negative
49997  i am a cathol taught in parochi elementari sch...  negative
49998  im go to have to disagre with the previou comm...  negative
49999  no one expect the star trek movi to be high ar...  negative

[49582 rows x 2 columns]

In [17]:
#Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['sentiment']=le.fit_transform(data['sentiment'])

In [18]:
y=data['sentiment']
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [19]:
#Vectorixation -TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(max_features=5000)
x=tf.fit_transform(data['review'])

In [20]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5871114 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3122)	0.02032251735685024
  (0, 3097)	0.09542098470744526
  (0, 4440)	0.20903467205715237
  (0, 3151)	0.057164905655617715
  (0, 3688)	0.04795018941759714
  (0, 2023)	0.024837126680226217
  (0, 2809)	0.05093623457657249
  (0, 4438)	0.06274954229236089
  (0, 162)	0.032260181258981106
  (0, 4820)	0.07851591273828991
  (0, 2475)	0.04850405470299644
  (0, 3184)	0.43216782713328356
  (0, 1533)	0.10274122058172444
  (0, 4987)	0.05287089753313154
  (0, 442)	0.05711365014241208
  (0, 2178)	0.07161368973329611
  (0, 4455)	0.024446041394784856
  (0, 300)	0.041296577361905513
  (0, 3711)	0.08249984253761973
  (0, 323)	0.07507443472841555
  (0, 4460)	0.04274859304710011
  (0, 2386)	0.1295866356729789
  (0, 1581)	0.05594527309388424
  (0, 4864)	0.049933268194460693
  (0, 2051)	0.04118502050404425
  :	:
  (49581, 2285)	0.09370049477083149
  (49581, 1653)	0.16515065743591884
  (49581, 2206)	0.0807050171213464
  (49581, 4603)	0.09124520635183705
  (49581, 774)	0.10606814986101117
  (49581, 3827)	0.0969614002395767
  (49581, 2523)	0.10984319095358464
  (49581, 4659)	0.0994442296449171
  (49581, 2585)	0.09254382643575335
  (49581, 2353)	0.13974759078626203
  (49581, 378)	0.11062351220232874
  (49581, 2059)	0.12366306939993575
  (49581, 3639)	0.10501109054108233
  (49581, 2266)	0.1603929003910312
  (49581, 317)	0.10474191443679787
  (49581, 4584)	0.1548917714869443
  (49581, 2511)	0.17800008244249405
  (49581, 4160)	0.1951942180887046
  (49581, 1087)	0.15522934182669346
  (49581, 681)	0.1432055922664932
  (49581, 3024)	0.15987763334791602
  (49581, 2942)	0.16869126598604967
  (49581, 776)	0.12541386082039135
  (49581, 1955)	0.1531895792131522
  (49581, 3640)	0.14696302897312627

In [21]:
#Train-Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [22]:
import numpy as np

In [23]:
# Re-run train_test_split to ensure X_train and X_test are correctly initialized as sparse matrices
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, random_state=42, test_size=0.2)

X_train=X_train.toarray()
X_test=X_test.toarray()

In [24]:
print(X_train)

[[0.21579409 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [25]:
#Load data
import torch
from torch.utils.data import TensorDataset,DataLoader
trainset=TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(Y_train.values).float()
)
testset=TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(Y_test.values).float()
)

In [26]:
train_load=DataLoader(trainset,shuffle=True,batch_size=32)
test_load=DataLoader(testset,shuffle=True,batch_size=32)

Build RNN Model

In [28]:
import torch.nn as nn
import torch.optim as optim

In [29]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0)
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [31]:
input_size = X_train.shape[1]
model = RNN(input_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

In [34]:
#Train The Model

epochs=10
for epoch in range(epochs):
  model.train()
  for xb,yb in train_load:
    optimizer.zero_grad()
    xb=xb.unsqueeze(1)
    output=model(xb)
    outputs = torch.sigmoid(output.squeeze())
    loss=criterion(outputs,yb)
    loss.backward()
    optimizer.step()
  print(f"for {epoch} loss={loss.item()}")

for 0 loss=0.08460008352994919
for 1 loss=0.10865044593811035
for 2 loss=0.09114249795675278
for 3 loss=0.4353552758693695
for 4 loss=0.3150603771209717
for 5 loss=0.21391017735004425
for 6 loss=0.14336924254894257
for 7 loss=0.07822424173355103
for 8 loss=0.26197534799575806
for 9 loss=0.11491014808416367

In [36]:
#Evaluation
# evaluate

model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0

    for Xb, yb in test_load:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 87.48613491983463